# Generated by Django 4.1.1 on 2022-10-12 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_class_creator'),
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.school')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.class')),
            ],
        ),
    ]
