# Generated by Django 4.1.1 on 2022-10-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='creator',
        ),
    ]
