# Generated by Django 4.1.1 on 2022-10-16 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_studentaccount'),
        ('manager', '0003_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timefrom', models.TimeField()),
                ('timeto', models.TimeField()),
                ('s_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacheraccount')),
            ],
        ),
    ]
