# Generated by Django 4.1.1 on 2022-10-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_lesson_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
