# Generated by Django 4.1.2 on 2022-10-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
